name: Publish NuGet.org

on:
  push:
    branches: [ main ]

env:
  TARGET_PROJECT: ./src/JpCalendar/JpCalendar.csproj
  CONFIGURATION: Release
  DOTNET_VERSION: 8
  OUTPUT_DIR: ./nuget

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ${{ env.TARGET_PROJECT }}
    
    - name: Pack
      run: dotnet pack ${{ env.TARGET_PROJECT }} --configuration ${{ env.CONFIGURATION }} --output ${{ env.OUTPUT_DIR }}

    - name: Publish
      run: dotnet nuget push ${{ env.OUTPUT_DIR }}/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
